{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "titan-aas.fullname" . }}-secret
  labels:
    {{- include "titan-aas.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "titan-aas.databaseUrl" . | quote }}
  REDIS_URL: {{ include "titan-aas.redisUrl" . | quote }}
  {{- if .Values.secrets.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
{{- end }}
